name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - Linux
        - Mac OS
        - Other
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Botania CEu Version
    validations:
      required: true
  - type: textarea
    id: other-mods
    attributes:
      label: Other installed mods
      description: If you're playing a modpack, make sure the issue can be reproduced using the latest version of Botania CEu and no other mods. If it can't, send the list of mods necessary to reproduce this with their versions (for example, a latest.log file usually has a list of mods), or a link to the modpack version you're playing. Note that if the list of mods in here is large, you may be asked to bisect the issue (this is not a guarantee).
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
